"""HealthProgram  table

Revision ID: 5633ebaf1734
Revises: 
Create Date: 2025-04-25 14:32:57.345152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5633ebaf1734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clientname', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_clientname'), ['clientname'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_gender'), ['gender'], unique=False)

    op.create_table('doctor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctorname', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctorname')
    )
    op.create_table('health_program',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('programname', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programname')
    )
    op.create_table('enrollment',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['health_program.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'program_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    op.drop_table('health_program')
    op.drop_table('doctor')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_gender'))
        batch_op.drop_index(batch_op.f('ix_client_clientname'))

    op.drop_table('client')
    # ### end Alembic commands ###
